### ISSUE TITLE
"ReferenceError: WebSocketServerStream is not defined" when requiring WebSocketJSONStream

### ISSUE THREAD

**Issue by alexsobrino87** [avital/websocket-json-stream#1]
Hi,

Whenever I try to include websocket-json-stream in one of my project it crashes the applicatoin with the following error:

> /NodeJS/node_modules/websocket-json-stream/index.js:23
> util.inherits(WebSocketServerStream, Duplex);
>               ^
> 
> ReferenceError: WebSocketServerStream is not defined
>     at Object.<anonymous> (/NodeJS/node_modules/websocket-json-stream/index.js:23:15)
>     at Module._compile (module.js:435:26)... etc

   I am new to any implementation of websockets, perhaps there is a deprecated library or a pre-requisite outside nodejs that I am not getting?

Thank you!

**Comment by avital** [comment]
Thanks for noticing! I fixed this change at version 0.0.3.
